name: color_picker
description: A modern desktop color picker application for Windows and macOS.
version: 1.0.0
publish_to: 'none'
homepage: https://github.com/Pimzino/ColorPicker
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hotkey_manager: ^0.1.8
  window_manager: ^0.3.7
  screen_retriever: ^0.1.9
  win32: ^5.1.1
  ffi: ^2.1.0
  provider: ^6.1.1
  shared_preferences: ^2.3.4
  intl: ^0.20.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
